source: ./_src
destination: ./html
asset_pipeline:
  bundle: false
  compress: false
markdown: kramdown
mini_magick:
  thumbnail:
    source: assets/img/photos/original
    destination: assets/img/photos/thumbnail
    resize: "100x100"
  medium:
    source: assets/img/photos/original
    destination: assets/img/photos/medium
    resize: "800x600"
